# Generated by Django 5.0 on 2024-03-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db',
            name='uploader',
        ),
    ]
