# Generated by Django 5.0 on 2024-03-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_db_bio_alter_db_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db',
            name='image',
        ),
    ]
