# Generated by Django 5.0 on 2024-03-05 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_db_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='templated/images'),
            preserve_default=False,
        ),
    ]
